services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
    volumes:
      - db-data:/bitnami/postgresql
    restart: always

volumes:
  db-data: